name: flutter_delivery_tool
description: A sigle-click delivery tool for your Flutter app.
version: 0.0.1
maintainer: Mark Abramenko (@markander)

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  path: ^1.8.0
  io: ^1.0.4
  yaml: ^3.1.1
  args: ^2.2.0
  json_annotation: ^4.8.0
  checked_yaml: ^2.0.2
  cli_util: ^0.3.5

dev_dependencies:
  test: ^1.16.0
  json_serializable: ^6.6.0
  build_runner: ^2.3.3
  lints: ^2.0.1
